name: lint
on:
  # When Release Pull Request is merged
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  CI: true
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Bootstrap project
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: install
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: |
            - recursive: false
              args: [--frozen-lockfile]
      - name: build
        run: pnpm run build
      - name: lint
        run: pnpm run example test
        env:
          CI: true
        
      